name = "quaff_asserts"
version = "0.7.3"
license = "MIT"
author = "Brad Richardson"
maintainer = "everythingfunctional@protonmail.com"
copyright = "2020 Brad Richardson"

[dependencies]
quaff = { git = "https://gitlab.com/everythingfunctional/quaff.git" }
iso_varying_string = { git = "https://gitlab.com/everythingfunctional/iso_varying_string.git", tag = "v3.0.2" }
strff = { git = "https://gitlab.com/everythingfunctional/strff.git", tag = "v3.0.4" }
veggies = { git = "https://gitlab.com/everythingfunctional/veggies", tag = "v1.0.3" }
